# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://github.com/riverarchitect
title: River Architect
email: river.architect.program [at] gmail.edu
author: The River Architect Development Team
description: the next generation river design
copyright: 'Copyright &copy; 2019 The River Architect Development Team. All Rights Reserved.'
credits: 'Credits: <a href="https://www.yubawater.org/">https://www.yubawater.org/</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/RiverArchitect/program/
  - title: install
    url: https://riverarchitect.github.io/RA_wiki/Installation
  - title: wiki
    url: https://riverarchitect.github.io/RA_wiki/main_page
